create database practise1;
use practise1;
create table Mech(s_id int,s_name varchar(25));
START TRANSACTION;
insert into Mech values (101,'jayanth');
SAVEPOINT A;
update mech set s_id=102 where s_id = 101;
SAVEPOINT B;
insert into mech values(103, 'Kartik');
select* from mech;
SAVEPOINT C;
select* from mech;
ROLLBACK TO B;
select * from mech;
commit;